apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: obo-web
  name: obo-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obo-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: obo-web
    spec:
      containers:
        - image: duylinh158/techmaster-obo-web:1.2
          name: techmaster-obo-web
          envFrom:
          - configMapRef:
              name: obo-web-config
          resources: {}
status: {}
